package com.application.todolist.controllers;

import com.application.todolist.entities.User;
import com.application.todolist.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path="/user")
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addUser(@RequestParam(required = false) String name,
                   @RequestParam(required = false) String email,
                   @RequestParam(required = false) String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setUsername(email);
        n.setPassword(password);
        userRepository.save(n);
        return "User saved";
    }
}
